# application.yml

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ehauiele@gmail.com
    password: EHA123456
    port: 586
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false